name: Build and push Docker image

on:
  push:
    branches:
      - main
      - work

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPONAME: ${{ vars.DOCKER_REPONAME }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure Docker repository name is available
        id: repo-name
        run: |
          if [ -z "${DOCKER_REPONAME}" ] && [ -z "${{ secrets.DOCKER_REPONAME }}" ]; then
            echo "Repository name is not configured. Set DOCKER_REPONAME as a repository variable or secret." >&2
            exit 1
          fi
          if [ -z "${DOCKER_REPONAME}" ]; then
            echo "DOCKER_REPONAME=${{ secrets.DOCKER_REPONAME }}" >> "$GITHUB_ENV"
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_REPONAME }}
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
